- name: Setup SourcePawn Compiler
  uses: rumblefrog/setup-sp@v1.1.0
steps:
- uses: actions/checkout@v1

- uses: rumblefrog/setup-sp@master
  with:
    version: '1.10.x'

- run: spcomp -iAnotherIncludeDirectory plugin.sp -o output/plugin.smx